# iot-analytics/values.yaml
# Global values inherited by all subcharts

global:
  namespace: atakangul-dev
  imageRegistry: image-registry.openshift-image-registry.svc:5000/atakangul-dev

# Enable/disable subcharts
infra:
  enabled: true

apps:
  enabled: true

monitoring:
  enabled: true

ci-cd:
  enabled: true